"""
Execution report generator for the Outlook Tencent Meeting hybrid pipeline.

Dual-backend token tracking:
  - Claude Code: reads session JSONL logs (~/.claude/projects/<proj>/<session>.jsonl)
  - Hermes Agent: reads SQLite state.db (LOCALAPPDATA/hermes/state.db)

Detected automatically via CLAUDE_CODE_SESSION_ID env var:
  - Present → Claude Code JSONL path
  - Absent  → Hermes SQLite path

Token reporting is built into compose.py (baseline auto-captured on compose,
report generated by report.py finalize, called after all step screenshots).
Use report.py standalone only for debugging:

  python report.py baseline          # Print baseline (uuid for CC, tokens for Hermes)
  python report.py generate          # Generate report manually
      --to user@example.com \
      --start "2026-07-03 09:00" \
      --end "2026-07-03 11:00" \
      --baseline <uuid>
"""
import sys
import os
import json
import argparse
import sqlite3
import tempfile
from datetime import datetime
from _shared import STATE_FILE, dispatch_outlook_app


# ── Backend detection ─────────────────────────────────────────────────────

def is_claude_code():
    """True if running under Claude Code (JSONL backend), False for Hermes (SQLite)."""
    return bool(os.environ.get("CLAUDE_CODE_SESSION_ID", ""))


# ── Hermes SQLite helpers ─────────────────────────────────────────────────

HERMES_DB_PATH = None
HERMES_BASELINE_FILE = None

def _hermes_db():
    """Return the Hermes state.db path."""
    global HERMES_DB_PATH
    if HERMES_DB_PATH is None:
        HERMES_DB_PATH = os.path.join(os.environ.get("LOCALAPPDATA", ""), "hermes", "state.db")
    return HERMES_DB_PATH

def _hermes_baseline_file():
    """Return the Hermes token baseline temp file path."""
    global HERMES_BASELINE_FILE
    if HERMES_BASELINE_FILE is None:
        HERMES_BASELINE_FILE = os.path.join(tempfile.gettempdir(), "hermes_tokens_baseline.txt")
    return HERMES_BASELINE_FILE

def capture_hermes_baseline():
    """Capture current token counts from Hermes state.db and write to baseline file.

    Returns the baseline string "input|output|cache|api_count" or None on failure.
    """
    db = _hermes_db()
    baseline_path = _hermes_baseline_file()
    try:
        conn = sqlite3.connect(db, timeout=2)
        cur = conn.execute(
            "SELECT input_tokens, output_tokens, cache_read_tokens, api_call_count "
            "FROM sessions WHERE ended_at IS NULL ORDER BY started_at DESC LIMIT 1"
        )
        row = cur.fetchone()
        conn.close()
        if row is None:
            print("WARNING: No active Hermes session found — baseline not captured.",
                  file=sys.stderr)
            return None
        baseline_str = f"{row[0]}|{row[1]}|{row[2]}|{row[3]}"
        with open(baseline_path, "w") as f:
            f.write(baseline_str)
        print(f"[report] Hermes baseline written: {baseline_str}")
        return baseline_str
    except sqlite3.OperationalError as e:
        print(f"WARNING: Hermes token tracking unavailable ({e}) — baseline not captured.",
              file=sys.stderr)
        return None

def read_hermes_baseline():
    """Read the baseline string from the Hermes baseline file.

    Returns "input|output|cache|api_count" or None if not found.
    """
    baseline_path = _hermes_baseline_file()
    if not os.path.exists(baseline_path):
        return None
    try:
        with open(baseline_path, "r") as f:
            return f.read().strip()
    except IOError:
        return None

def calc_hermes_token_delta(baseline_str):
    """Calculate token delta from Hermes baseline string vs current state.db.

    Returns (input_t, output_t, cache_t, api_count_delta).
    """
    if not baseline_str:
        return 0, 0, 0, 0
    try:
        parts = baseline_str.split("|")
        base_in = int(parts[0])
        base_out = int(parts[1])
        base_cache = int(parts[2])
        base_api = int(parts[3])
    except (ValueError, IndexError):
        print("WARNING: Invalid Hermes baseline format.", file=sys.stderr)
        return 0, 0, 0, 0

    db = _hermes_db()
    try:
        conn = sqlite3.connect(db, timeout=2)
        cur = conn.execute(
            "SELECT input_tokens, output_tokens, cache_read_tokens, api_call_count "
            "FROM sessions WHERE ended_at IS NULL ORDER BY started_at DESC LIMIT 1"
        )
        row = cur.fetchone()
        conn.close()
        if row is None:
            print("WARNING: No active Hermes session for delta calculation.",
                  file=sys.stderr)
            return 0, 0, 0, 0
        delta_in = row[0] - base_in
        delta_out = row[1] - base_out
        delta_cache = row[2] - base_cache
        delta_api = row[3] - base_api
        return delta_in, delta_out, delta_cache, delta_api
    except sqlite3.OperationalError as e:
        print(f"WARNING: Hermes delta calculation failed ({e}).", file=sys.stderr)
        return 0, 0, 0, 0


# ── Path helpers ──────────────────────────────────────────────────────────

def get_session_jsonl_path():
    """Resolve the current session's JSONL file from env vars.

    Searches all project directories under ~/.claude/projects/ for the
    session JSONL — does NOT depend on os.getcwd(), so it works
    regardless of where the script is invoked from.
    """
    session_id = os.environ.get("CLAUDE_CODE_SESSION_ID", "")
    if not session_id:
        # Fallback: scan .claude/sessions/ for the active session
        home = os.path.expanduser("~")
        sessions_dir = os.path.join(home, ".claude", "sessions")
        try:
            for fname in os.listdir(sessions_dir):
                if fname.endswith(".json"):
                    fpath = os.path.join(sessions_dir, fname)
                    with open(fpath, "r") as f:
                        d = json.load(f)
                    if d.get("status") == "busy":
                        session_id = d["sessionId"]
                        break
        except FileNotFoundError:
            pass
    if not session_id:
        print("ERROR: Cannot determine CLAUDE_CODE_SESSION_ID.", file=sys.stderr)
        sys.exit(1)

    home = os.path.expanduser("~")
    projects_dir = os.path.join(home, ".claude", "projects")
    target_file = f"{session_id}.jsonl"

    # Search all project directories — cwd-independent
    if os.path.isdir(projects_dir):
        for proj_name in os.listdir(projects_dir):
            jsonl_path = os.path.join(projects_dir, proj_name, target_file)
            if os.path.isfile(jsonl_path):
                return jsonl_path

    # Should never reach here if the session is active
    print(f"ERROR: Session JSONL not found: {target_file}", file=sys.stderr)
    print(f"  Searched under: {projects_dir}", file=sys.stderr)
    sys.exit(1)


def read_jsonl(path):
    with open(path, "r", encoding="utf-8") as f:
        return [json.loads(line) for line in f]


# ── baseline subcommand ───────────────────────────────────────────────────

def cmd_baseline():
    """Print the baseline: uuid for Claude Code, token string for Hermes."""
    if is_claude_code():
        # Claude Code: print uuid of most recent assistant message
        jsonl_path = get_session_jsonl_path()
        lines = read_jsonl(jsonl_path)
        for line in reversed(lines):
            if line.get("type") == "assistant":
                print(line["uuid"])
                return
        print("ERROR: No assistant message found in session.", file=sys.stderr)
        sys.exit(1)
    else:
        # Hermes: capture current token counts to baseline file
        baseline = capture_hermes_baseline()
        if baseline:
            print(f"Baseline captured: {baseline}")
        else:
            print("WARNING: Hermes baseline not captured.", file=sys.stderr)


# ── generate subcommand ───────────────────────────────────────────────────

def calc_token_delta(jsonl_path, baseline_uuid):
    """Sum token usage from all assistant messages AFTER baseline_uuid."""
    lines = read_jsonl(jsonl_path)
    found = False
    input_t = output_t = cache_t = 0
    count = 0

    for line in lines:
        if line.get("type") != "assistant":
            continue
        if not found:
            if line.get("uuid") == baseline_uuid:
                found = True
            continue
        usage = line.get("message", {}).get("usage", {})
        input_t += usage.get("input_tokens", 0)
        output_t += usage.get("output_tokens", 0)
        cache_t += usage.get("cache_read_input_tokens", 0)
        count += 1

    if not found:
        print(f"WARNING: baseline uuid {baseline_uuid} not found in session.", file=sys.stderr)
    return input_t, output_t, cache_t, count


def get_meeting_from_calendar(date_str):
    """Query Outlook Calendar via COM for meetings on date_str (YYYY-MM-DD)."""
    try:
        import win32com.client
        outlook = dispatch_outlook_app()
        cal = outlook.GetNamespace("MAPI").GetDefaultFolder(9)  # olFolderCalendar
        items = cal.Items
        items.Sort("[Start]")
        restriction = f"[Start] >= '{date_str} 00:00' AND [Start] < '{date_str} 23:59'"
        results = []
        for item in items.Restrict(restriction):
            results.append({
                "subject": item.Subject,
                "start": str(item.Start),
                "end": str(item.End),
                "attendees": item.RequiredAttendees or "",
                "location": item.Location or "",
            })
        return results
    except Exception as e:
        print(f"WARNING: Calendar query failed: {e}", file=sys.stderr)
        return []


def extract_meeting_id(location_url):
    """Extract meeting ID from Tencent Meeting URL or Location string.

    This is a fallback path used when compose-time body extraction didn't
    store a meeting_id in state. Extracts from the URL:
      - Dashed ID in URL: https://meeting.tencent.com/dm/123-456-789
      - Plain 9-digit: https://meeting.tencent.com/dm/123456789
      - Last resort: URL slug (alias, not the dial-in number)
    """
    import re
    if not location_url:
        return ""
    # Match 9+ digits with optional dash separators: 123456789 or 123-456-789
    dash_match = re.search(r'(\d{3}(?:-\d{3}){2,})', location_url)
    if dash_match:
        return dash_match.group(1)
    # Match plain 9-digit number anywhere in the string
    plain_match = re.search(r'(?<!\d)(\d{9,10})(?!\d)', location_url)
    if plain_match:
        return plain_match.group(1)
    # Last resort: last URL path segment
    parts = location_url.rstrip("/").split("/")
    last = parts[-1] if parts else ""
    last = last.split("?")[0]
    return last


def _fmt_duration(seconds):
    """Format a duration in seconds to a human-readable string."""
    if seconds < 1:
        return "<1s"
    if seconds < 60:
        return f"{seconds}s"
    m, s = divmod(seconds, 60)
    return f"{m}m {s}s"


def print_execution_report(to, start_str, end_str, meetings, input_t,
                           output_t, cache_t, msg_count, snapshots=None,
                           started_at=None, step_times=None, lang="zh",
                           subject="", return_data=False,
                           state_meeting_id=""):
    """Print the formatted execution report to stdout.

    Called from cmd_finalize() after all step screenshots are captured.

    snapshots: optional dict mapping step key to file path, e.g.
               {"step3": "C:/.../step3_meeting_form.png"}
    step_times: optional dict mapping step key to ISO-format timestamp,
                used to calculate per-step durations.
    lang: "zh" for Chinese (default), "en" for English
    return_data: if True, return a data dict suitable for report_html.py
    state_meeting_id: meeting ID extracted from body at compose time
                       (preferred over calendar re-fetch to avoid item.Body)
    """
    snapshots = snapshots or {}
    step_times = step_times or {}

    # Calculate per-step durations
    step_durations = {}
    if step_times and started_at:
        try:
            keys = ["step1", "step2", "step3", "step4", "step5"]
            # Use earliest available timestamp as the effective start —
            # handles cases where compose.py's started_at post-dates
            # step1/step2 captures (capture_snapshot.py sets started_at
            # on first capture, but older state files may lack it).
            effective_start = datetime.fromisoformat(started_at) if isinstance(started_at, str) else started_at
            for key in keys:
                if key in step_times:
                    ts = datetime.fromisoformat(step_times[key])
                    if ts < effective_start:
                        effective_start = ts
            prev_dt = effective_start
            for key in keys:
                if key in step_times:
                    cur_dt = datetime.fromisoformat(step_times[key])
                    step_durations[key] = int((cur_dt - prev_dt).total_seconds())
                    prev_dt = cur_dt
        except (ValueError, TypeError):
            pass

    # ── i18n labels ──────────────────────────────────────────────────────
    if lang == "en":
        L = {
            "title": "══ Outlook Tencent Invitation — Execution Report ══",
            "params": "Meeting Parameters:",
            "subject": "Subject",
            "attendee": "Attendee",
            "time": "Time",
            "meeting_link": "Meeting Link",
            "meeting_id": "Meeting ID",
            "waiting_room": "Waiting Room",
            "enabled": "Enabled",
            "not_found": "<not found>",
            "pipeline": "Pipeline:",
            "step1": "Step 1   Classic Outlook + Clear Popups    ✓",
            "step2": "Step 2   Schedule Meeting + WR             ✓",
            "step3": 'Step 3   COM compose                        ✓  --to {to} --start "{start}" --end "{end}"',
            "step4": "Step 4   COM send                           ✓",
            "step5": "Step 5   Calendar Verification              ✓  {date} found {n} meeting(s), Location matched",
            "token_usage": "Token Usage:",
            "input_tokens": "Input tokens",
            "output_tokens": "Output tokens",
            "total_tokens": "Total tokens",
            "duration": "Duration",
            "status": "Status: All 5 steps passed ✓",
        }
    else:
        L = {
            "title": "══ Outlook Tencent Invitation — 执行报告 ══",
            "params": "会邀参数:",
            "subject": "主题",
            "attendee": "收件人",
            "time": "时间",
            "meeting_link": "会议链接",
            "meeting_id": "会议号",
            "waiting_room": "Waiting Room",
            "enabled": "已启用",
            "not_found": "<未找到>",
            "pipeline": "执行流水线:",
            "step1": "Step 1   确认经典Outlook + 清理弹窗   ✓",
            "step2": "Step 2   Schedule Meeting + WR        ✓",
            "step3": 'Step 3   COM compose                  ✓  --to {to} --start "{start}" --end "{end}"',
            "step4": "Step 4   COM send                     ✓",
            "step5": "Step 5   Calendar 验证                ✓  {date} 找到 {n} 个会议, Location 匹配",
            "token_usage": "Token 消耗:",
            "input_tokens": "输入 tokens",
            "output_tokens": "输出 tokens",
            "total_tokens": "总计 tokens",
            "duration": "总耗时",
            "status": "状态: 全部 5 步通过 ✓",
        }

    location = ""
    meeting_id = state_meeting_id  # Prefer compose-time extraction (no item.Body needed)
    if meetings:
        # 1. Prefer subject + start-time match (exact: same subject AND same start)
        if subject:
            for m in meetings:
                if m["subject"] == subject and start_str in m["start"]:
                    location = m["location"]
                    meeting_id = meeting_id or extract_meeting_id(location)
                    break
        # 2. Fall back: subject match only (if no subject+start match)
        if not location and subject:
            for m in meetings:
                if m["subject"] == subject:
                    location = m["location"]
                    meeting_id = meeting_id or extract_meeting_id(location)
                    break
        # 3. Fall back to start-time match (pick last = most recent)
        if not location:
            for m in reversed(meetings):
                if start_str in m["start"]:
                    location = m["location"]
                    break
        # 4. Last resort: end-time match
        if not location:
            for m in meetings:
                if end_str in m["end"]:
                    location = m["location"]
                    break
    # Fallback: extract from URL if state had no meeting_id
    if not meeting_id and location:
        meeting_id = extract_meeting_id(location)

    total = input_t + output_t

    # Extract date for display
    try:
        dt = datetime.strptime(start_str, "%Y-%m-%d %H:%M")
    except ValueError:
        try:
            dt = datetime.strptime(start_str, "%Y-%m-%d %H:%M:%S")
        except ValueError:
            dt = None
    date_str = dt.strftime("%Y-%m-%d") if dt else start_str[:10]

    # Helper: render a snapshot link as project-relative path only
    def snapshot_link(step_key):
        path = snapshots.get(step_key)
        if path:
            try:
                rel = os.path.relpath(path, os.getcwd())
            except (ValueError, OSError):
                rel = path
            rel = rel.replace("\\", "/")
            return f"\n    📷 {rel}"
        return ""

    # Calculate wall-clock duration if started_at is available
    elapsed_str = ""
    if started_at:
        # Use the same effective_start logic as per-step durations for consistency
        effective_start = datetime.fromisoformat(started_at) if isinstance(started_at, str) else started_at
        if step_times:
            for ts_str in step_times.values():
                ts = datetime.fromisoformat(ts_str)
                if ts < effective_start:
                    effective_start = ts
        elapsed = datetime.now() - effective_start
        total_seconds = int(elapsed.total_seconds())
        if total_seconds < 60:
            elapsed_str = f"{total_seconds}s"
        elif total_seconds < 3600:
            elapsed_str = f"{total_seconds // 60}m {total_seconds % 60}s"
        else:
            h = total_seconds // 3600
            m = (total_seconds % 3600) // 60
            s = total_seconds % 60
            elapsed_str = f"{h}h {m}m {s}s"

    print(L["title"])
    print()
    print(L["params"])
    print(f"  {L['subject']}:     {subject or L['not_found']}")
    print(f"  {L['attendee']}:     {to}")
    print(f"  {L['time']}:       {start_str} – {end_str.split()[-1] if ' ' in end_str else end_str} (UTC+8)")
    print(f"  {L['meeting_link']}:   {location or L['not_found']}")
    print(f"  {L['meeting_id']}:     {meeting_id or L['not_found']}")
    print(f"  {L['waiting_room']}:  {L['enabled']}")
    print()
    print(L["pipeline"])
    print()
    dur = lambda k: f" ({_fmt_duration(step_durations[k])})" if k in step_durations else ""

    print(f"  {L['step1']}{dur('step1')}{snapshot_link('step1')}")
    print(f"  {L['step2']}{dur('step2')}{snapshot_link('step2')}")
    step3_line = L['step3'].format(to=to, start=start_str, end=end_str)
    if subject:
        step3_line += f' --subject "{subject}"'
    print(f"  {step3_line}{dur('step3')}{snapshot_link('step3')}")
    print(f"  {L['step4']}{dur('step4')}{snapshot_link('step4')}")
    print(f"  {L['step5'].format(date=date_str, n=len(meetings))}{dur('step5')}{snapshot_link('step5')}")
    print()
    print(L["token_usage"])
    print(f"  {L['input_tokens']}:   {input_t:,}")
    print(f"  {L['output_tokens']}:   {output_t:,}")
    print(f"  {L['total_tokens']}:   {total:,}")
    print()
    if elapsed_str:
        print(f"{L['duration']}:    {elapsed_str}")
        print()
    print(L["status"])

    # ── Return data dict for report_html.py ──
    if return_data:
        data_out = {
            "subject": subject,
            "to": to,
            "start": start_str,
            "end": end_str,
            "meeting_link": location,
            "meeting_id": meeting_id,
            "waiting_room": True,
            "steps": [],
            "token_usage": {"input": input_t, "output": output_t, "total": total},
            "duration": elapsed_str,
            "lang": lang,
            "snapshot_dir": "",
            "model": "",
        }
        step_descs = {
            "step1": L["step1"].split("   ")[1].split("   ")[0].strip() if "   " in L["step1"] else "",
            "step2": L["step2"].split("   ")[1].split("   ")[0].strip() if "   " in L["step2"] else "",
            "step3": "COM compose",
            "step4": "COM send + verify",
            "step5": "Calendar verify",
        }
        for key in ["step1", "step2", "step3", "step4", "step5"]:
            entry = {
                "name": key.replace("step", "Step "),
                "desc": step_descs.get(key, key),
                "status": "PASS",
            }
            if key in snapshots:
                entry["snapshot"] = snapshots[key]
            if key in step_durations:
                entry["duration"] = _fmt_duration(step_durations[key])
            data_out["steps"].append(entry)
        return data_out
    return None


def cmd_generate(args):
    """Generate the full execution report."""
    if is_claude_code():
        # Claude Code: use JSONL backend
        jsonl_path = get_session_jsonl_path()
        input_t, output_t, cache_t, msg_count = calc_token_delta(jsonl_path, args.baseline)
    else:
        # Hermes: use SQLite backend
        baseline_str = read_hermes_baseline()
        if not baseline_str:
            print("ERROR: No Hermes baseline found. Run 'report.py baseline' first.", file=sys.stderr)
            sys.exit(1)
        input_t, output_t, cache_t, msg_count = calc_hermes_token_delta(baseline_str)

    # Extract date for calendar query
    try:
        dt = datetime.strptime(args.start, "%Y-%m-%d %H:%M")
        date_str = dt.strftime("%Y-%m-%d")
    except ValueError:
        date_str = args.start[:10]

    meetings = get_meeting_from_calendar(date_str)

    # Load snapshots from compose state if available
    snapshots = {}
    try:
        if os.path.exists(STATE_FILE):
            with open(STATE_FILE, "r", encoding="utf-8") as f:
                state = json.load(f)
            snapshots = state.get("snapshots", {})
    except Exception:
        pass

    lang = args.lang if hasattr(args, 'lang') and args.lang else "zh"
    print_execution_report(args.to, args.start, args.end, meetings,
                           input_t, output_t, cache_t, msg_count,
                           snapshots=snapshots if snapshots else None,
                           lang=lang, subject=args.subject)


def cmd_finalize(args):
    """Generate the final execution report from compose state.

    Reads compose state (written by compose.py compose + capture_snapshot.py
    --update-state-key calls for steps 1-5), calculates token delta, queries
    Calendar, and prints the full report with all snapshot links.
    Cleans up the state file on success.
    """
    if not os.path.exists(STATE_FILE):
        print("ERROR: No compose state file found.", file=sys.stderr)
        print("  Expected at:", STATE_FILE, file=sys.stderr)
        sys.exit(1)

    with open(STATE_FILE, "r", encoding="utf-8") as f:
        state = json.load(f)

    # Validate required keys
    missing = [k for k in ("baseline", "to", "start", "end") if k not in state]
    if missing:
        print(f"ERROR: Compose state missing required keys: {missing}",
              file=sys.stderr)
        print(f"  State content: {json.dumps(state, ensure_ascii=False)[:500]}",
              file=sys.stderr)
        sys.exit(1)

    # Calculate token delta using the appropriate backend
    if is_claude_code():
        jsonl_path = get_session_jsonl_path()
        input_t, output_t, cache_t, msg_count = calc_token_delta(
            jsonl_path, state["baseline"]
        )
    else:
        baseline_str = read_hermes_baseline()
        if not baseline_str:
            print("ERROR: No Hermes baseline found. Run 'report.py baseline' first.", file=sys.stderr)
            sys.exit(1)
        input_t, output_t, cache_t, msg_count = calc_hermes_token_delta(baseline_str)

    # Extract date for calendar query
    try:
        dt = datetime.strptime(state["start"], "%Y-%m-%d %H:%M")
        date_str = dt.strftime("%Y-%m-%d")
    except ValueError:
        date_str = state["start"][:10]

    meetings = get_meeting_from_calendar(date_str)
    snapshots = state.get("snapshots", {})

    # Subject: prefer compose-time state (reliable), fall back to
    # Calendar COM query if state is missing (e.g. older state file).
    subject = state.get("subject", "")
    if not subject and meetings:
        target_start = state["start"]
        for m in meetings:
            if target_start in m.get("start", ""):
                subject = m.get("subject", "")
                break

    lang = args.lang if hasattr(args, 'lang') and args.lang else "zh"

    # Meeting ID: prefer compose-time extraction from body (no item.Body needed)
    state_meeting_id = state.get("meeting_id", "")

    # ── Print report and get data dict for HTML sidecar ──
    report_data = print_execution_report(
        state["to"], state["start"], state["end"], meetings,
        input_t, output_t, cache_t, msg_count,
        snapshots=snapshots if snapshots else None,
        started_at=state.get("started_at"),
        step_times=state.get("step_times"),
        lang=lang, subject=subject,
        return_data=True,
        state_meeting_id=state_meeting_id,
    )

    # ── Export JSON sidecar for report_html.py ──
    if report_data:
        # Fill snapshot_dir from first available snapshot
        if snapshots:
            first_snap = next(iter(snapshots.values()))
            report_data["snapshot_dir"] = os.path.dirname(first_snap)
        # Merge agent-provided model name
        model = args.model if hasattr(args, 'model') and args.model else ""
        if model:
            report_data["model"] = model
        # Add step details for Step 3 and Step 5
        for step in report_data["steps"]:
            if step["name"] == "Step 3":
                step["detail"] = f'--to {state["to"]} --start "{state["start"]}" --end "{state["end"]}"'
                if subject:
                    step["detail"] += f' --subject "{subject}"'
            elif step["name"] == "Step 5" and meetings:
                date_d = state["start"][:10]
                step["detail"] = f"{date_d} found {len(meetings)} meeting(s), Location matched"
        # Write JSON sidecar alongside state file
        output_json_path = STATE_FILE + ".html_report.json"
        with open(output_json_path, "w", encoding="utf-8") as f:
            json.dump(report_data, f, ensure_ascii=False, indent=2)
        print(f"\n[report] HTML data exported to: {output_json_path}")

    # Clean up state file after successful report
    try:
        os.remove(STATE_FILE)
    except OSError:
        pass


# ── main ──────────────────────────────────────────────────────────────────

def setup_utf8_stdout():
    """Force UTF-8 output on Windows to avoid GBK encoding errors."""
    if sys.platform == "win32":
        sys.stdout.reconfigure(encoding="utf-8", errors="replace")


def main():
    setup_utf8_stdout()
    parser = argparse.ArgumentParser(
        description="Outlook Tencent Meeting — execution report generator"
    )
    parser.add_argument("--lang", choices=["zh", "en"], default="zh",
                        help="Output language: zh (default) or en")
    sub = parser.add_subparsers(dest="cmd", required=True)

    sub.add_parser("baseline", help="Print baseline uuid (run BEFORE task)")

    gen = sub.add_parser("generate", help="Generate full execution report (run AFTER task)")
    gen.add_argument("--to", required=True, help="Meeting attendees")
    gen.add_argument("--subject", default="", help="Meeting subject")
    gen.add_argument("--start", required=True, help="Meeting start time (YYYY-MM-DD HH:MM)")
    gen.add_argument("--end", required=True, help="Meeting end time (YYYY-MM-DD HH:MM)")
    gen.add_argument("--baseline", required=True, help="Baseline uuid from 'baseline' command")

    fin = sub.add_parser("finalize", help="Generate final report from compose state "
                        "(includes all step snapshots, cleans up state)")
    fin.add_argument("--model", default="",
                      help="LLM model name for HTML report (e.g. glm-5-turbo)")

    args = parser.parse_args()
    if args.cmd == "baseline":
        cmd_baseline()
    elif args.cmd == "generate":
        cmd_generate(args)
    elif args.cmd == "finalize":
        cmd_finalize(args)


if __name__ == "__main__":
    main()
